# Generated by Django 2.2.12 on 2020-05-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0003_subjectmodel_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('year', models.CharField(max_length=4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteapp.SubjectModel')),
            ],
        ),
    ]
