# Generated by Django 2.2.12 on 2020-05-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0009_imagemodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='when',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
